#!/bin/sh
echo "adding cron to save last known path to the Internet"
sed "\| \* \* \* .*last_internet_path.*|d" -i /etc/crontabs/root
echo "*/30 * * * * /usr/sbin/internet_path > /tmp/internet_path_output; if [ -s /tmp/internet_path_output ]; then cp /tmp/internet_path_output /etc/last_internet_path; fi" >> /etc/crontabs/root

